### ISSUE TITLE
Crear interfaz con el botón para abrir la cámara

### ISSUE THREAD

**Issue by angeltrevinov** [ProyectoIntegrador2018/inventario_seguro#7]
### Crear interfaz con el botón para abrir la cámara

Utilizar el prototipo inicial para 
- [x]  Agregar boton para abrir la camara
- [x]  Agregar botón de registro manual
- [x] Agregar constraints

**Comment by angeltrevinov** [comment]
@MsMemes Puedes agregar el otro botón y darles una mejor presentación con los constraints?

**Comment by MsMemes** [comment]
Claro
